#!/bin/bash

# Railway Deployment Helper - UniVault Research Backend
# This script provides instructions for deploying to Railway

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Railway Deployment Helper - UniVault Backend               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}📋 Deployment Checklist${NC}"
echo ""
echo "Before deploying to Railway, ensure:"
echo ""
echo "1. Prerequisites:"
echo "   ☐ GitHub account created"
echo "   ☐ Code committed to GitHub"
echo "   ☐ Railway account created (https://railway.app)"
echo ""
echo "2. Environment Variables Ready:"
echo "   ☐ NODE_ENV: production"
echo "   ☐ JWT_SECRET: strong random string (64+ chars)"
echo "   ☐ FRONTEND_URL: your frontend URL"
echo "   ☐ PORT: 5000"
echo ""
echo "3. Code Ready:"
echo "   ☐ backend/package.json exists"
echo "   ☐ backend/Dockerfile exists"
echo "   ☐ backend/src/server.js exists"
echo "   ☐ All code committed to git"
echo ""

echo -e "${BLUE}🚀 Deployment Steps${NC}"
echo ""
echo "1. Go to https://railway.app"
echo "2. Log in with your GitHub account"
echo "3. Create new project"
echo "4. Select 'Deploy from GitHub'"
echo "5. Authorize Railway to access your repos"
echo "6. Select 'UniVault-Research' repository"
echo "7. Railway auto-detects backend/Dockerfile"
echo ""

echo -e "${BLUE}⚙️  Environment Variables to Set${NC}"
echo ""
echo "In Railway dashboard, go to Variables and add:"
echo ""
echo "NAME: NODE_ENV"
echo "VALUE: production"
echo ""
echo "NAME: JWT_SECRET"
echo "VALUE: [Run: node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\"]"
echo ""
echo "NAME: FRONTEND_URL"
echo "VALUE: https://your-frontend-url.vercel.app"
echo "       (Update after deploying frontend)"
echo ""
echo "NAME: PORT"
echo "VALUE: 5000"
echo ""

echo -e "${BLUE}🔑 Generate JWT_SECRET${NC}"
echo ""
echo "Run this command to generate a secure random string:"
echo ""
echo "  node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\""
echo ""
echo "Copy the output and use as JWT_SECRET in Railway"
echo ""

echo -e "${BLUE}✅ After Deployment${NC}"
echo ""
echo "1. Check Deployments tab for 'Active' status"
echo "2. Review Logs - should see:"
echo "   '🚀 Server is running on http://localhost:5000'"
echo "3. Copy Public URL from Railway dashboard"
echo "4. Test health endpoint:"
echo "   curl https://your-railway-url/api/health"
echo "5. Save URL for frontend configuration"
echo ""

echo -e "${BLUE}🔗 Public URL Format${NC}"
echo ""
echo "Your backend will be accessible at:"
echo "https://your-service-name.railway.app/api"
echo ""
echo "Example endpoints:"
echo "  POST   https://your-service-name.railway.app/api/auth/register"
echo "  POST   https://your-service-name.railway.app/api/auth/login"
echo "  GET    https://your-service-name.railway.app/api/health"
echo ""

echo -e "${BLUE}📊 Verify Deployment${NC}"
echo ""
echo "Test your backend is running:"
echo ""
echo "# Health check"
echo "curl https://your-railway-url/api/health"
echo ""
echo "# Register user"
echo "curl -X POST https://your-railway-url/api/auth/register \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"name\":\"Test\",\"email\":\"test@test.com\",\"password\":\"test123\"}'"
echo ""

echo -e "${BLUE}🆘 Troubleshooting${NC}"
echo ""
echo "Issue: Build failed"
echo "  → Check build logs in Railway Deployments tab"
echo "  → Ensure package.json syntax is correct"
echo "  → Verify Node version (18+ required)"
echo ""
echo "Issue: Server won't start"
echo "  → Check JWT_SECRET is set"
echo "  → Verify NODE_ENV=production"
echo "  → Check logs for specific error"
echo ""
echo "Issue: Can't connect from frontend"
echo "  → Update FRONTEND_URL in Railway"
echo "  → Update frontend VITE_API_URL to Railway URL"
echo "  → Check CORS is working"
echo ""
echo "Issue: CORS error in browser"
echo "  → Ensure FRONTEND_URL matches frontend domain"
echo "  → Backend already has CORS configured"
echo "  → Restart service after variable changes"
echo ""

echo -e "${BLUE}📚 Documentation${NC}"
echo ""
echo "For detailed information:"
echo "  • RAILWAY_DEPLOYMENT.md    - Full Railway guide"
echo "  • QUICK_DEPLOY.md          - Quick start guide"
echo "  • DEPLOYMENT.md            - All deployment options"
echo "  • API.md                   - API endpoints reference"
echo ""

echo -e "${GREEN}✨ You're ready to deploy!${NC}"
echo ""
echo "Next: Visit https://railway.app and follow the deployment steps above"
echo ""
